### ISSUE TITLE
Unable to connect to MQTT on GCP from Android

### ISSUE THREAD

**Issue by individual8** [owntracks/quicksetup#69]
Earlier today I installed Owntracks on a VM with quicksetup. Everything seems to up and running. I can check the frontend and logged in on the server and got myself the config for the Android app. 

However the Android app would only run via HTTP, not MQTT. Seems like MQTT cannot be accessed from outside with the provided config? It is running, I checked on the VM's console. Please help!

This is what I get in the logs:
```
2024-11-24 16:44:52.641 I [DefaultDispatcher-worker-5] MQTTMessageProcessorEndpoint$connectToBroker: Connecting to ssl://offliner.net:8883?# timeout = 30s
2024-11-24 16:45:22.752 E [DefaultDispatcher-worker-5] MQTTMessageProcessorEndpoint$connectToBroker: MQTT client unable to connect to endpoint
MqttException (0) - java.net.SocketTimeoutException: failed to connect to offliner.net/34.32.64.230 (port 8883) from /192.168.2.138 (port 38516) after 30000ms
	at androidx.work.impl.utils.WorkForegroundUpdater$1.run(SourceFile:233)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.net.SocketTimeoutException: failed to connect to offliner.net/34.32.64.230 (port 8883) from /192.168.2.138 (port 38516) after 30000ms
	at libcore.io.IoBridge.connectErrno(IoBridge.java:235)
	at libcore.io.IoBridge.connect(IoBridge.java:179)
	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
	at java.net.Socket.connect(Socket.java:646)
	at org.conscrypt.AbstractConscryptSocket.connect(SourceFile:7)
	at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(SourceFile:50)
	at org.eclipse.paho.client.mqttv3.internal.SSLNetworkModule.start(SourceFile:3)
	at androidx.work.impl.utils.WorkForegroundUpdater$1.run(SourceFile:66)
	... 6 more
```

**Comment by individual8** [comment]
Mosquitto is up and running:
`systemctl status mosquitto
● mosquitto.service - Mosquitto MQTT Broker
     Loaded: loaded (/lib/systemd/system/mosquitto.service; enabled; preset: enabled)
     Active: active (running) since Sun 2024-11-24 15:39:08 UTC; 10s ago
       Docs: man:mosquitto.conf(5)
             man:mosquitto(8)
    Process: 16049 ExecStartPre=/bin/mkdir -m 740 -p /var/log/mosquitto (code=exited, status=0/SUCCESS)
    Process: 16050 ExecStartPre=/bin/chown mosquitto /var/log/mosquitto (code=exited, status=0/SUCCESS)
    Process: 16051 ExecStartPre=/bin/mkdir -m 740 -p /run/mosquitto (code=exited, status=0/SUCCESS)
    Process: 16052 ExecStartPre=/bin/chown mosquitto /run/mosquitto (code=exited, status=0/SUCCESS)
   Main PID: 16053 (mosquitto)
      Tasks: 1 (limit: 1136)
     Memory: 1.5M
        CPU: 32ms
     CGroup: /system.slice/mosquitto.service
             └─16053 /usr/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf`

**Comment by jpmens** [comment]
Judging by the log, the error is clear: `MQTT client unable to connect to endpoint .. offliner.net/34.32.64.230 (port 8883)`

Which, if I try it, is accurate. Is there a firewall fronting that TCP port?

**Comment by individual8** [comment]
It's a VM in GCP. I probably have to create some additional rules in its network config?!

**Comment by jpmens** [comment]
Are you asking us? LoL. 
I don't know.

**Comment by jpmens** [comment]
You will need to have the app connect to TCP/8883 on your VM. If the domain you configured in `configuration.yaml` points to the address of your VM and 8883 passes in you should be seeing positions reported. Best way to test, IMO, is to 

```console
$ sudo tail -f /var/log/mosquitto/mosquitto.log
```

while you publish a position from your smartphone: top right, up-arrow on the map page.

**Comment by individual8** [comment]
> Which, if I try it, is accurate. Is there a firewall fronting that TCP port?

This it was! I added a Firewall rule as explained here: https://stackoverflow.com/questions/21065922/how-to-open-a-specific-port-such-as-9090-in-google-compute-engine

Now it works! Thx for your support.

**Comment by jpmens** [comment]
Glad you got it working.
